### ISSUE TITLE
Do not put multiple awaits in for loops! Make queries in parallel instead.

### ISSUE THREAD

**Issue by ngwattcos** [cornell-dti/DesignAtCornell#59]
https://github.com/cornell-dti/DesignAtCornell/blob/ed731448356b80f25d19fef4c3da6d66d8ff8099/server/scripts/import_roster_v2.ts#L41

### Problems
1. _**The `/* eslint-disable no-await-in-loop */` linting disable check is problematic.**_ It is there to guard against the practices used in this function.

2. As discussed in [DevSesh #2](https://tinyurl.com/devsesh-sp22-two), you should avoid making queries in repeated components or in loops!

3. Ignoring the above, `await <Promise>` should always be used as an expression (assigned to a variable or returned).

We can solve all three with the following:

Since there are no dependencies between each `axios` call in the for loop, calls can be made concurrently.

Make multiple queries concurrently by combining **`Promise.allSettled`** and functional programming!! Here's a psuedocode:

```
async function getRosterCourses(coursesOne: identifierAndDA[], classUrl: string, currSem: string) {
  // map each course name to axios request
  return await Promise.allSettled(coursesOne.map(
    // fetch each course object
    course => axios.get(`${classUrl + course.identifier[0]}&q=${course.identifier[1]}`)))
    // filter by failed
    .then(queriedCourses => queriedCourses.filter(queriedCourse => queriedCourse.status === "rejected"));
}

```

This makes retrieving missed courses much faster (it's done concurrently). It also presents the code much more cleanly in a functional matter (and concisely). We also addressed the problem that the `no-await-in-loop` check guards against

`Promise.allSettled` allows multiple promises to run in parallel and fulfills exactly when all promises either get `fulfilled` or `rejected`. Please see the [`Promise` API docs for more details on `allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled).

**Comment by rohanmaheshwari430** [comment]
Resolved! Thank you for the insight!
